### ISSUE TITLE
Trailing slash in Resource UI

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-resource-gui#3]
On Marmotta we still have the issue that by default the Resource UI seems to add a trailing slash to the entry URI which does not work. Once I delete it manually all works fine.

Sample: http://data.fusepool.info:8205/?defaultContainer=http://data.fusepool.info:8181/ldp/

**Comment by cblakeley** [comment]
Virtuoso requires all LDPC URIs to be slash terminated, so any fix needs to accommodate this difference between Marmotta and VOS.

**Comment by retog** [comment]
I'm a bit confused, trying the URI provided by @ktk the trailing slash gets actually removed. I think things should work with any compliant LDP implementation if the resource-gui neither adds nor removes trailing slashes, never. @szluca could you look into this?

**Comment by szluca** [comment]
It seems like data.fusepool.info uses an old version of the resource gui. It _used to_ ignore trailing slashes because it seemed to be a good solution but in the latest version [it's not anymore](https://github.com/fusepoolP3/p3-resource-gui/blob/master/src/main/webapp/js/listRes_functions.js#L222).

**Comment by ktk** [comment]
Yes sorry when I posted the issue data.fusepool.info was on the newest release. Due to the Marmotta issues I had to switch back to the old release which didn't had that problem yet.

**Comment by retog** [comment]
I think as far as the resource gui is concerned, things are correct. Maybe the ldp root in Marmotta is http://data.fusepool.info:8181/ldp without trailing slash.

**Comment by ktk** [comment]
Everything in Marmotta is without trailing slash. That's the issue :-D

**Comment by retog** [comment]
Closing the issue here as this doesn't seem to be a resource-gui issue.

**Comment by ktk** [comment]
I don't get that, where does it have to be fixed then?

**Comment by retog** [comment]
Where do you get the URI http://data.fusepool.info:8205/?defaultContainer=http://data.fusepool.info:8181/ldp/ from? This URI indicated that there is a container at http://data.fusepool.info:8181/ldp/ but the container is at http://data.fusepool.info:8181/ldp.
I just tried it with the platform on localhost pointing to a correct LDP root and it didn't work, so I'm not sure if this will actually fix the problem: https://github.com/fusepoolP3/p3-platform-reference-implementation/commit/8dc107b4a4a8d7395364a50209ff1fd7a85ca369
In principle things should work since the resolution of #2, but I don't fins any commit associated to that issue!

**Comment by retog** [comment]
Found the commit resolving #2: https://github.com/fusepoolP3/p3-resource-gui/commit/991cb10a4f9a1876d89d50b19ebb2ccd80f726e0 - It's helpful to reference the issue in the commit message
